### ISSUE TITLE
FC layers of roi_head wasn't be pruned

### ISSUE THREAD

**Issue by mls1999725** [jshilong/FisherPruning#13]
Hi, when I finetune the faster rcnn ( flops 50%, act 64% ), FC layers of roi_head wasn't be pruned, I wonder is it normal?
![image](https://user-images.githubusercontent.com/43207078/139149539-46a532d8-ee7e-4a5e-8f0c-c2121150b7bc.png)

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
