### ISSUE TITLE
How compute the speedup on GPUs?

### ISSUE THREAD

**Issue by mls1999725** [jshilong/FisherPruning#15]
Hi, I wonder how to compute speedup on GPUs? Is it the total inference time of CPU divide by that on GPU? If so, I wonder how to calculate the total time on the CPU by mmdetection, do I need to put all the data on the CPU for retraining? Or just need to put the data on the CPU during inference? 
![tempsnip](https://user-images.githubusercontent.com/43207078/139538544-66260cb4-603c-490c-b277-ca10cbfbfbc9.png)
Looking forward to reply！

**Comment by liyangliu** [comment]
The time is measured on a single GPU with batchsize=64 as done in RegNet.

**Comment by mls1999725** [comment]
Thanks for reply! I wonder do you mean all models including detection models need to be done in RegNet, if I want to compute the speedup on GPUs?

**Comment by liyangliu** [comment]
We follow the "settings" in the RegNet paper (https://arxiv.org/abs/2003.13678, not a specific "model") to measure the inference speed on a 2080 GPU.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
