### ISSUE TITLE
Is there any error in Table 5 of original paper?

### ISSUE THREAD

**Issue by mls1999725** [jshilong/FisherPruning#16]
Hi, I wonder if this line in Table 5 is wrong? It should be Faster-I
![tempsnip](https://user-images.githubusercontent.com/43207078/139831310-e0bccd34-3a09-4b72-ab9f-4d23ad1d517a.png)

**Comment by liyangliu** [comment]
There is no error, the second Faster-M prunes more FLOPs than the first one.

**Comment by mls1999725** [comment]
Thanks!

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
