### ISSUE TITLE
An issue about running the code

### ISSUE THREAD

**Issue by MaltoseFlower** [jshilong/FisherPruning#17]
I create a virtual environment, open-mmlab, with python=3.7, pytorch=1.3.0, cudatoolkit=10.0, mmcv=1.3.16, mmdet=2.13.0.
However, it still can not run.

File "tools/train.py", line 16, in <module>                                                                           
    from mmdet.apis import set_random_seed, train_detector
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by MaltoseFlower** [comment]
could you please tell me how to solve this problem? More details are as follow:
Firstly, I used conda to create a virtual environment with python 3.7 and torch 1.3.0, cudatoolkit=10.0.
Then, due to conda cannot install mmcv-full 1.3.16 that is compatible with torch 1.3.0, I used pip to install mmcv 1.3.16.
pip install mmcv-full==1.3.16 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.3.0/index.html
And I alse used pip to install mmdet 2.13.0.

**Comment by jshilong** [comment]
I recommend you build the corresponding mmcv-full by yourself， and you can use `CUDA_HOME` to specify your cuda version.
