### ISSUE TITLE
Some questions about the paper and code

### ISSUE THREAD

**Issue by syswyl** [jshilong/FisherPruning#18]
Thanks for the great work, I have some questions about this code
1. In the paper you mentioned coupled channels, I understand what it means is that C2/C5 (you described in Figure 4) receive the same input. Is there any other meaning besides this?
<img width="598" alt="截屏2022-01-10 上午10 30 32" src="https://user-images.githubusercontent.com/29301581/148712035-9c8d5c09-d618-4b06-b7f2-cefcfbe44148.png">
2. For this common concat operation in yolo, can your code still handle it normally？Because the input comes from two ancestors, and it seems that the number of channels cannot correspond to the function **def construct_outchannel_masks(self)** to construct the mask，
<img width="488" alt="截屏2022-01-10 上午10 35 54" src="https://user-images.githubusercontent.com/29301581/148712295-5f4ace55-a43a-4077-b8bf-3d5f9f31835b.png">
Hope to get your reply.

**Comment by jshilong** [comment]
duplicate to #19
