### ISSUE TITLE
How prune the FC layer?

### ISSUE THREAD

**Issue by mls1999725** [jshilong/FisherPruning#4]
Hi, I tried to complete the codes of pruning faster rcnn, but I don't know how to prune the FC layer in roi_head. I have finished the twostage_wrapper function as shown below
![twostage](https://user-images.githubusercontent.com/43207078/137929126-0e0a6330-c7fb-4977-8014-6f10d42b6908.PNG)
But I got error.
![error](https://user-images.githubusercontent.com/43207078/137929162-82e1c699-d809-4c65-8ffe-998c79c0db74.PNG)
Could you help me see where the problem is? Thanks!

**Comment by hangrymoon01** [comment]
@mls1999725 can you post the solution for faster rcnn please. Much appreciated.

**Comment by mls1999725** [comment]
I am pruning faster rcnn now. If the finetuned results are reasonable, I will open the source codes in case any problems arise.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
