### ISSUE TITLE
How compute the acts of FC layer?

### ISSUE THREAD

**Issue by mls1999725** [jshilong/FisherPruning#6]
Hi, I'm trying to complete the pruning codes of FC layer. I wonder how to compute the acts of FC layer, is it n times oc where n is the batch size and oc is the channel numbers of output feature?

**Comment by mls1999725** [comment]
Thanks! By the way, I wonder how to add fisher information when conv and fc in one group? They have different in_channels.
When I add fisher information, the error is
![image](https://user-images.githubusercontent.com/43207078/138111255-a9f6e129-ad40-4256-980f-7d9df4827975.png)
And these two modules are in one group but the conv has 256 in_channels and the fc has 12544 in_channels.
![image](https://user-images.githubusercontent.com/43207078/138111427-cdb8f4d5-f940-433e-9bd6-4432827f68b9.png)

**Comment by liyangliu** [comment]
Please refer to the last paragraph of Sec. 3.2 in the original paper.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
